In [1]:
import pandas as pd

data = pd.read_csv('Data/general_data.csv')

In [2]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 7048 entries, 0 to 7047
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Start_Time   7048 non-null   str
 1   Size(MB)     7048 non-null   float64
 2   SkillID      7048 non-null   str
 3   Operator     7048 non-null   str
 4   BagName      7048 non-null   str
 5   Duration(s)  7048 non-null   float64
 6   Station      7048 non-null   str
 7   IsValid      7048 non-null   bool
 8   SkillName    7048 non-null   str
dtypes: bool(1), float64(2), str(6)
memory usage: 1.0 MB

In [3]:
data[data['IsValid']==True]

,Start_Time,Size(MB),SkillID,Operator,BagName,Duration(s),Station,IsValid,SkillName
0,2026-01-30T09:41:14Z,2612.05,SKILL_017,d_vargas,SKILL_017_20260130_094114,543.35,1,True,Put pasta in ziploc bags
2,2026-01-30T09:57:36Z,948.96,SKILL_018,d_vargas,SKILL_018_20260130_095736,209.58,1,True,Close bags with twist ties
3,2026-01-30T09:52:37Z,923.89,SKILL_018,d_vargas,SKILL_018_20260130_095237,199.90,1,True,Close bags with twist ties
5,2026-01-30T10:02:15Z,608.43,SKILL_018,d_vargas,SKILL_018_20260130_100215,140.53,1,True,Close bags with twist ties
6,2026-02-02T14:06:16Z,8252.25,SKILL_003,d_vargas,SKILL_003_20260202_140616,228.19,2,True,Organize screwdriver bits
...,...,...,...,...,...,...,...,...,...
7031,2026-02-18T07:41:55Z,5777.67,SKILL_023,e_cabezas,SKILL_023_20260218_074155,610.45,03,True,Built up box (Present)
7037,2026-02-18T10:28:47Z,2117.07,SKILL_024,e_martinez,SKILL_024_20260218_102847,216.63,04,True,Put hooks on shower courtain
7038,2026-02-18T09:54:58Z,2627.87,SKILL_013,e_martinez,SKILL_013_20260218_095458,268.83,04,True,Set up a hand lamp
7042,2026-02-18T07:44:51Z,2406.93,SKILL_014,l_aguilera,SKILL_014_20260218_074451,228.75,04,True,Fasten nuts onto bolts
7046,2026-02-18T10:34:57Z,2763.13,SKILL_024,e_martinez,SKILL_024_20260218_103457,273.31,04,True,Put hooks on shower courtain

In [4]:
data[data['IsValid']==False]

,Start_Time,Size(MB),SkillID,Operator,BagName,Duration(s),Station,IsValid,SkillName
1,2026-01-30T10:34:15Z,181.49,SKILL_021,d_vargas,SKILL_021_20260130_103415,24.14,1,False,Build Up Box (Mailer)
4,2026-01-30T10:48:08Z,28.47,SKILL_022,d_vargas,SKILL_022_20260130_104808,4.07,1,False,Build Up Box (Regular ECT)
7,2026-01-30T10:45:58Z,378.33,SKILL_022,d_vargas,SKILL_022_20260130_104558,45.37,1,False,Build Up Box (Regular ECT)
8,2026-01-30T10:56:16Z,434.53,SKILL_023,d_vargas,SKILL_023_20260130_105616,89.45,1,False,Built up box (Present)
16,2026-01-30T10:42:15Z,352.19,SKILL_022,d_vargas,SKILL_022_20260130_104215,75.10,1,False,Build Up Box (Regular ECT)
...,...,...,...,...,...,...,...,...,...
7041,2026-02-18T10:16:48Z,733.23,SKILL_040,e_martinez,SKILL_040_20260218_101648,101.51,04,False,Fasten a belt
7043,2026-02-18T12:30:48Z,1499.30,SKILL_004,l_aguilera,SKILL_004_20260218_123048,150.92,04,False,Set Screwdriver package
7044,2026-02-18T14:06:44Z,3611.61,SKILL_003,e_martinez,SKILL_003_20260218_140644,479.90,04,False,Organize screwdriver bits
7045,2026-02-18T14:17:11Z,3127.85,SKILL_014,e_martinez,SKILL_014_20260218_141711,335.53,04,False,Fasten nuts onto bolts
7047,2026-02-18T10:08:19Z,2683.89,SKILL_012,e_martinez,SKILL_012_20260218_100819,321.80,04,False,Put pasta in jars

In [23]:
p = list(data['Operator'].unique())

In [24]:
p

['d_vargas',
 'c_becerra',
 'n_mora',
 'l_aguilera',
 'e_martinez',
 'a_rodriguez',
 'JUAN',
 'Juan',
 'juan',
 'C_BECERRA',
 'C_becerra',
 'h_alcaraz',
 'D_vargas',
 'H_alcaraz',
 'N_mora',
 'N_MORA',
 'H_ALCARAZ',
 'D_VARGAS',
 'L_AGUILERA',
 'E_MARTINEZ',
 'e_cabezas']

In [27]:
p.insert(0,None)

In [28]:
print(p)

[None, 'd_vargas', 'c_becerra', 'n_mora', 'l_aguilera', 'e_martinez', 'a_rodriguez', 'JUAN', 'Juan', 'juan', 'C_BECERRA', 'C_becerra', 'h_alcaraz', 'D_vargas', 'H_alcaraz', 'N_mora', 'N_MORA', 'H_ALCARAZ', 'D_VARGAS', 'L_AGUILERA', 'E_MARTINEZ', 'e_cabezas', None]

In [29]:
opes = list(data['Operator'].unique())

In [30]:
opes

['d_vargas',
 'c_becerra',
 'n_mora',
 'l_aguilera',
 'e_martinez',
 'a_rodriguez',
 'JUAN',
 'Juan',
 'juan',
 'C_BECERRA',
 'C_becerra',
 'h_alcaraz',
 'D_vargas',
 'H_alcaraz',
 'N_mora',
 'N_MORA',
 'H_ALCARAZ',
 'D_VARGAS',
 'L_AGUILERA',
 'E_MARTINEZ',
 'e_cabezas']